server.port=8080
spring.application.name=BrightMinds Tuition API

# PostgreSQL Database
spring.datasource.url=SPRING_DATASOURCE_URL
spring.datasource.username=SPRING_DATASOURCE_USERNAME
spring.datasource.password=SPRING_DATASOURCE_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# H2 disabled
spring.h2.console.enabled=false